data:
  raw: gs://mlops-2026-ramzan1/raw/data_raw.csv
  preprocessed: gs://mlops-2026-ramzan1/preprocessed/data_preprocessed.csv
  train: gs://mlops-2026-ramzan1/splits/train.csv
  test: gs://mlops-2026-ramzan1/splits/test.csv

split:
  target: Obesity
  test_size: 0.2
  random_state: 42
  stratify: true

train:
  n_estimators: 100
  max_depth: 15
  random_state: 42
  model_dir: models